Proposal for edits to the revised charter
opengeospatial/pubsub pull request #3
Opened 2023-06-26 11:28 UTC by cportele

2023-06-28 15:55 UTC, chris-little commented
@cportele stadnards -> standards
Also, I would prefer 
`OGC API Standards specify Web based capabilities which are typically based on polling for collection resource updates (new or changed or deleted features/records, coverages, maps, etc.). Depending on a collection's temporal resolution or frequency of updates, an event-driven / Publish-Subscribe architecture provides a timely, efficient and low latency approach for delivery of data updates.`
to read something like:
`OGC API Standards specify Web based capabilities which are typically based on polling for collection resource updates (new or changed or deleted features/records, coverages, maps, data, etc.). Depending on a collection's temporal resolution or frequency of updates or size, an event-driven / Publish-Subscribe architecture provides a timely, efficient and low latency approach for delivery of data updates or notifications.`

2023-07-04 11:50 UTC, ghobona approved these changes

2023-07-04 19:27 UTC, tomkralidis requested changes

2023-07-04 19:27 UTC, tomkralidis commented on charter/PubSub_SWG_Charter.adoc
> +The scope of the {titletext} is confined to enabling basic publish/subscribe functionality for resources from existing and future OGC API Stadnards. New filtering techniques will not be addressed, bu
`s/Stadnards/Standards/g`

2023-07-05 07:08 UTC, cportele commented on charter/PubSub_SWG_Charter.adoc
> +The scope of the {titletext} is confined to enabling basic publish/subscribe functionality for resources from existing and future OGC API Stadnards. New filtering techniques will not be addressed, bu
Thanks, fixed.

2023-07-05 07:10 UTC, cportele commented
@chris-little - Thanks. I have fix the typo and added two of your three changes. I have not added "data", because it is a generic term and not a resource type in the OGC API standards.

2023-07-05 10:59 UTC, merged

2023-07-05 11:01 UTC, chris-little reviewed
@cportele Thank you. But `data` is a resource type for OGC API-EDR.